-- Validation rules for the enrollment object.
INSERT INTO public.validation_rules
  (name, description, related_object, condition_config, block_on_status, block_on_event, error_message, owner_id, created_by)
VALUES
  ('Enrollment requires an owner',
   'Every enrollment must have a named owner at creation (platform-wide rule).',
   'enrollments', '{"check":"field_required","field":"enrollment_owner"}'::jsonb,
   NULL, 'before_insert',
   'Owner is required. Assign a named owner before saving the enrollment.',
   'c5a01ec8-960f-42ab-8a9e-a49822de89af','c5a01ec8-960f-42ab-8a9e-a49822de89af'),
  ('Enrollment requires a property',
   'Every enrollment is a child of a property; the property relationship is required.',
   'enrollments', '{"check":"field_required","field":"property_id"}'::jsonb,
   NULL, 'before_insert',
   'Property is required. Link this enrollment to a property before saving.',
   'c5a01ec8-960f-42ab-8a9e-a49822de89af','c5a01ec8-960f-42ab-8a9e-a49822de89af'),
  ('Enrollment requires a record type',
   'Enrollment record type (state + housing type) must be set before the record can be verified.',
   'enrollments', '{"check":"field_required","field":"enrollment_record_type"}'::jsonb,
   'Enrollment To Be Verified', 'before_update',
   'Enrollment cannot move to To Be Verified — no record type set. Choose a record type (e.g. WI-IRA-MF) first.',
   'c5a01ec8-960f-42ab-8a9e-a49822de89af','c5a01ec8-960f-42ab-8a9e-a49822de89af'),
  ('Enrollment requires a determination before verification',
   'The income-qualification determination must be run (qualifying mode populated) before the enrollment can be verified.',
   'enrollments', '{"check":"field_required","field":"enrollment_qualifying_mode"}'::jsonb,
   'Enrollment To Be Verified', 'before_update',
   'Enrollment cannot move to To Be Verified — income qualification has not been run. Run Income Qualification first.',
   'c5a01ec8-960f-42ab-8a9e-a49822de89af','c5a01ec8-960f-42ab-8a9e-a49822de89af'),
  ('Enrollment requires a document before submission',
   'At least one supporting document must be attached before submission.',
   'enrollments', '{"check":"document_count","value":1,"operator":">="}'::jsonb,
   'Enrollment Submitted — Awaiting Program Response', 'before_update',
   'Enrollment cannot be submitted — no supporting document attached. Run Income Qualification or upload the required proof first.',
   'c5a01ec8-960f-42ab-8a9e-a49822de89af','c5a01ec8-960f-42ab-8a9e-a49822de89af');
