-- "Amount" — the one column that carries an incentive application's money,
-- whichever program-specific field it was entered in.
--
-- Nicholas, 2026-08-29: "if our reports have two different record types and two
-- different field names that carry the amount... I don't want to rename these
-- fields on the different record types because they have different meanings and
-- they carry across in different ways, but I want these all to be in one column
-- on the final report."
--
-- Today an audit application's money sits in ia_requested_incentive_amount and a
-- project payment request's in ia_final_total_ira_homes_rebate_requested, and a
-- report can only total one column at a time — so RPT-00045 had two totals and
-- no answer to "how much".
--
-- This is a GENERATED column, and that choice is the point:
--
--   * A report calculated field would work on ONE report and could not be
--     totalled (the Σ control is on selected fields, not calc fields) — the
--     grand total is the whole reason this exists.
--   * A field_metadata FORMULA field is evaluated in the browser, on the record
--     page only (computeFieldValues in layoutService). Reports, list views and
--     dashboards read columns straight from Postgres and would never see it.
--   * A trigger-maintained column would be a second copy of the value that can
--     drift whenever a source field is written by a path the trigger misses.
--
-- Generated ALWAYS means Postgres computes it on every write, from the row
-- itself. It cannot drift, it cannot be edited, it needs no backfill, and it is
-- a real column — so it is available to every report, list view, filter, sort,
-- dashboard and export with no further work.
--
-- COALESCE, deliberately, NOT addition: no live row carries both amounts (0 of
-- 10 at the time of writing), and if one ever does, adding them would silently
-- double-count. First non-null wins, and the source fields keep their own names
-- and meanings — nothing is renamed, merged or deprecated.
--
-- The two record types that carry no amount at all today (WI-FOE,
-- WI-IRA-MF-HEAR) get NULL, which is the truth: they have no amount yet, and a
-- zero would read as "we asked for nothing".

ALTER TABLE public.incentive_applications
  ADD COLUMN IF NOT EXISTS ia_amount numeric(18,2)
  GENERATED ALWAYS AS (
    COALESCE(ia_requested_incentive_amount, ia_final_total_ira_homes_rebate_requested)
  ) STORED;

COMMENT ON COLUMN public.incentive_applications.ia_amount IS
  'Amount — the application''s money in one column, whichever program-specific field holds it: ia_requested_incentive_amount (audit applications), else ia_final_total_ira_homes_rebate_requested (project payment requests). Generated by the database on every write, so it cannot drift from its sources and cannot be edited. Add the next program''s amount field to the COALESCE when one appears.';

-- Declared as a computed field so no screen ever offers to edit it: the layout
-- overlay renders a `formula` field read-only with a FORMULA chip, and the
-- create pop-up leaves computed fields out. The expression is deliberately NULL
-- — the rule lives in the generated column above, and a copy of it here would
-- be a second definition free to disagree with the first (computeFieldValues
-- only evaluates a formula field that HAS an expression, so it leaves this one
-- alone and shows the stored value).
INSERT INTO public.field_metadata (
  fm_record_number, fm_object, fm_column, fm_label, fm_help_text, fm_description,
  fm_field_kind, fm_display_type, fm_data_type, fm_is_custom
)
SELECT
  '', 'incentive_applications', 'ia_amount', 'Amount',
  'The amount this application is asking for, whichever program field it was entered in.',
  'Computed by the database: the requested incentive amount when there is one, otherwise the final total IRA HOMES rebate requested. Read-only — edit the underlying program field instead.',
  'formula', 'currency', 'numeric', true
WHERE NOT EXISTS (
  SELECT 1 FROM public.field_metadata
  WHERE fm_object = 'incentive_applications' AND fm_column = 'ia_amount'
);

-- Prove the column agrees with its sources on every live row, rather than
-- assuming it. A generated column that disagreed would be a silent wrong number
-- on a financial report.
DO $$
DECLARE v_bad int;
BEGIN
  SELECT count(*) INTO v_bad
  FROM public.incentive_applications
  WHERE ia_is_deleted = false
    AND ia_amount IS DISTINCT FROM
        COALESCE(ia_requested_incentive_amount, ia_final_total_ira_homes_rebate_requested);
  IF v_bad > 0 THEN
    RAISE EXCEPTION 'ia_amount disagrees with its source columns on % row(s)', v_bad;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
